version: 2
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: pip install -U setuptools
      - run: pip install -U -r requirements.txt
      - run: pip install -U -r test-requirements.txt
      - run: python3 setup.py test --addopts "--cov . --cov-report term-missing --cov-report xml"
      - run: sudo pip install -U coverage codacy-coverage
      - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then python-codacy-coverage -r coverage.xml || echo "failed"; fi

  test_leaks_other:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: pip install -U setuptools
      - run: pip install -U -r requirements.txt
      - run: pip install -U -r test-requirements.txt
      - run: pip install -U pytest-openfiles pytest-leaks pytest-threadleak pytest-repeat
      - run: python3 setup.py test --addopts "--ignore=tests/tools/ --open-files --threadleak"

  build_trusty:
    docker:
      - image: qrledger/qrl-docker:trusty
    steps:
      - checkout
      - run: pip install -U setuptools
      - run: pip install -U -r requirements.txt
      - run: pip install -U -r test-requirements.txt
      - run: python3 --version
      - run: python3 setup.py test

  build_bionic:
    docker:
      - image: qrledger/qrl-docker:bionic
    steps:
      - checkout
      - run: pip install -U setuptools
      - run: pip install -U -r requirements.txt
      - run: pip install -U -r test-requirements.txt
      - run: python3 setup.py test

workflows:
  version: 2
  build_all:
    jobs:
      - build
#      - build_trusty
      - build_bionic

      - test_leaks_other
